title: uher3805's Portfolio
description: This is a test site to investigate the use of GH to build up an enterprise wiki. Thanks for contributing.
theme: just-the-docs

url: https://uher3805.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
